import type {
  Booking,
  PricingConfig,
  GosalaManager,
  Settlement,
  SlotHold,
} from "./types"

export const defaultPricing: PricingConfig = {
  standardMin: 60,
  extraUnitMin: 30,
  extraUnitRate: 500,
  freeKm: 5,
  perKm: 50,
  taxPct: 12,
  commissionPct: 20,
  maxDurationMin: 240,
  bufferMin: 30,
  rounding: "Nearest ₹10",
}

export const initialBookings: Booking[] = [
  {
    id: "GMA-24817",
    customer: "Ananya Deshmukh",
    phone: "+91 98204 11827",
    gosala: "Shri Krishna Gaushala",
    animal: "Gauri",
    animalType: "Cow",
    date: "26 Sep 2026",
    start: "10:00",
    end: "12:00",
    durationMin: 120,
    address: "14 Tulsi Nagar, Kothrud, Pune",
    distanceKm: 12.4,
    base: 3500,
    extraTime: 1000,
    transport: 370,
    addons: 450,
    tax: 468,
    discount: 0,
    total: 5788,
    commissionPct: 20,
    status: "Admin Review",
    driver: null,
    driverStage: 0,
    paid: true,
    managerRemark:
      "Feasibility confirmed. Gauri is in good health and rested for ceremonial service.",
    managerApproval: {
      userId: "MGR-801",
      name: "Gajanan Kale",
      timestamp: "26 Sep 2026, 09:35 AM",
      remark:
        "Feasibility confirmed. Gauri is in good health and rested for ceremonial service.",
    },
    freeKmSnapshot: 5,
    perKmSnapshot: 50,
    extraUnitRateSnapshot: 500,
    commissionSnapshot: 900,
    createdAt: "26 Sep 2026, 09:15 AM",
  },
  {
    id: "GMA-24816",
    customer: "Rohan Iyer",
    phone: "+91 99872 33410",
    gosala: "Nandini Goseva Sadan",
    animal: "Shyam",
    animalType: "Bull",
    date: "26 Sep 2026",
    start: "08:00",
    end: "09:00",
    durationMin: 60,
    address: "Plot 22, Baner Road, Pune",
    distanceKm: 4.2,
    base: 4200,
    extraTime: 0,
    transport: 0,
    addons: 300,
    tax: 360,
    discount: 250,
    total: 4610,
    commissionPct: 20,
    status: "Payment Verified",
    driver: null,
    driverStage: 0,
    paid: true,
    freeKmSnapshot: 5,
    perKmSnapshot: 50,
    extraUnitRateSnapshot: 500,
    commissionSnapshot: 840,
    createdAt: "26 Sep 2026, 07:45 AM",
  },
  {
    id: "GMA-24815",
    customer: "Meera Kulkarni",
    phone: "+91 98765 00921",
    gosala: "Shri Krishna Gaushala",
    animal: "Lakshmi",
    animalType: "Cow",
    date: "27 Sep 2026",
    start: "11:00",
    end: "12:30",
    durationMin: 90,
    address: "Sr 8, Viman Nagar, Pune",
    distanceKm: 9.1,
    base: 3500,
    extraTime: 500,
    transport: 205,
    addons: 650,
    tax: 428,
    discount: 0,
    total: 5283,
    commissionPct: 22,
    status: "Confirmed",
    driver: "Sunil Pawar",
    driverStage: 3,
    paid: true,
    managerRemark: "Operational check passed. Handler assigned.",
    managerApproval: {
      userId: "MGR-801",
      name: "Gajanan Kale",
      timestamp: "26 Sep 2026, 08:30 AM",
      remark: "Operational check passed. Handler assigned.",
    },
    adminRemark:
      "Final approval granted. Payment verified via Razorpay webhook.",
    adminApproval: {
      userId: "ADM-101",
      name: "Priya Sharma",
      timestamp: "26 Sep 2026, 08:45 AM",
      remark: "Final approval granted. Payment verified via Razorpay webhook.",
    },
    freeKmSnapshot: 5,
    perKmSnapshot: 50,
    extraUnitRateSnapshot: 500,
    commissionSnapshot: 880,
    createdAt: "26 Sep 2026, 08:00 AM",
  },
  {
    id: "GMA-24814",
    customer: "Vikram Joshi",
    phone: "+91 90045 71230",
    gosala: "Gopal Gaushala Trust",
    animal: "Kesari",
    animalType: "Calf",
    date: "27 Sep 2026",
    start: "09:00",
    end: "10:00",
    durationMin: 60,
    address: "Lane 5, Kalyani Nagar, Pune",
    distanceKm: 6.8,
    base: 2800,
    extraTime: 0,
    transport: 90,
    addons: 200,
    tax: 226,
    discount: 0,
    total: 3316,
    commissionPct: 20,
    status: "In Service",
    driver: "Arjun More",
    driverStage: 6,
    paid: true,
    createdAt: "26 Sep 2026, 07:15 AM",
  },
]

export const initialManagers: GosalaManager[] = [
  {
    id: "MGR-801",
    name: "Gajanan Kale",
    email: "gajanan@shrikrishnagosala.org",
    phone: "+91 98230 44102",
    gosala: "Shri Krishna Gaushala",
    region: "Pune West (Kothrud)",
    assignedDate: "12 Jan 2026",
    status: "Active",
    animalsCount: 3,
  },
  {
    id: "MGR-802",
    name: "Rameshwar Shinde",
    email: "rameshwar@nandinigoseva.org",
    phone: "+91 98901 88321",
    gosala: "Nandini Goseva Sadan",
    region: "Pune North (Baner)",
    assignedDate: "18 Feb 2026",
    status: "Active",
    animalsCount: 2,
  },
  {
    id: "MGR-803",
    name: "Tukaram Deshpande",
    email: "tukaram@gopaltrust.org",
    phone: "+91 97640 19283",
    gosala: "Gopal Gaushala Trust",
    region: "Pune East (Kalyani Nagar)",
    assignedDate: "05 Mar 2026",
    status: "Active",
    animalsCount: 2,
  },
  {
    id: "MGR-804",
    name: "Mahadev Joshi",
    email: "mahadev@vrindavangosala.org",
    phone: "+91 98500 77124",
    gosala: "Vrindavan Goshala",
    region: "Pune South (Hadapsar)",
    assignedDate: "20 May 2026",
    status: "Active",
    animalsCount: 1,
  },
  {
    id: "MGR-805",
    name: "Vitthal Patil",
    email: "vitthal@kamdhenuseva.org",
    phone: "+91 99220 63819",
    gosala: "Kamdhenu Seva Kendra",
    region: "Pune West (Wakad)",
    assignedDate: "14 Jun 2026",
    status: "Inactive",
    animalsCount: 1,
  },
]

export const initialSettlements: Settlement[] = [
  {
    gosala: "Shri Krishna Gaushala",
    bookings: 24,
    gross: 184500,
    commissionPct: 20,
    status: "Approved",
    batch: "SEP-W4",
  },
  {
    gosala: "Nandini Goseva Sadan",
    bookings: 18,
    gross: 142300,
    commissionPct: 20,
    status: "Processing",
    batch: "SEP-W4",
  },
  {
    gosala: "Gopal Gaushala Trust",
    bookings: 15,
    gross: 121800,
    commissionPct: 22,
    status: "Pending",
    batch: "SEP-W4",
  },
  {
    gosala: "Vrindavan Goshala",
    bookings: 9,
    gross: 68400,
    commissionPct: 20,
    status: "Paid",
    batch: "SEP-W3",
  },
  {
    gosala: "Kamdhenu Seva Kendra",
    bookings: 6,
    gross: 41200,
    commissionPct: 20,
    status: "Failed",
    batch: "SEP-W3",
  },
]

class InMemoryDB {
  bookings: Booking[] = [...initialBookings]
  managers: GosalaManager[] = [...initialManagers]
  settlements: Settlement[] = [...initialSettlements]
  pricingConfig: PricingConfig = { ...defaultPricing }
  slotHolds: SlotHold[] = []
  blockedSlots: Record<string, string[]> = {
    "Shyam-26 Sep 2026": ["11:00", "12:00"],
  }

  // Helpers
  cleanExpiredHolds() {
    const now = Date.now()
    this.slotHolds = this.slotHolds.filter((h) => h.expiresAt > now)
  }
}

export const db = new InMemoryDB()
